// <auto-generated />
namespace LojaVirtual.Infra.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LojaVirtual_V0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LojaVirtual_V0));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041742184_LojaVirtual_V0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
